// English text for the whole app. Inline markup: **bold**, *italic*,
// [link](url). {placeholders} are filled in by t(); plural entries have
// one/other (and few/many where a language needs them).

export default {
  meta: {
    title: 'Reservoir Computing Playground',
    description: 'Interactive reservoir computing demos: forecast chaos, recognise gestures and spoken words, and compute with a simulated bucket of water, all trained in milliseconds in your browser.',
  },

  nav: {
    home: 'Reservoir Computing Playground, home',
    brand: 'Reservoir Playground',
    demos: 'Demos',
    intro: 'Intro',
    chaos: 'Chaos',
    gestures: 'Gestures',
    speech: 'Speech',
    water: 'Water',
    theme: 'Colour theme: {theme} (click to change)',
    themes: { auto: 'automatic', light: 'light', dark: 'dark' },
    language: 'Language',
  },

  common: {
    level: { label: 'Explanation', simple: 'Simple', detailed: 'Detailed' },
    tryIt: 'Try it:',
    reset: '↺ Reset settings',
    resetDone: 'Settings are back to their defaults.',
    trainingTime: 'Training time',
    trainedWeights: 'Trained weights',
    neurons: 'Neurons',
    spectralRadius: 'Spectral radius',
    leak: 'Leak rate',
    reservoir: 'Reservoir',
    ms: 'ms',
    s: 's',
    older: '← older',
    now: 'now →',
    loadFailed: 'Sorry, this demo failed to load: {error}',
    footer: 'Everything runs locally in your browser and nothing is uploaded. Free software under the GNU GPL v3.',
    source: 'Source code',
  },

  intro: {
    title: 'Machine learning without training the network',
    hero: {
      simple: [
        'Throw a few pebbles into a pond and watch the ripples spread, bounce and mix. Look at the water a moment later and it still “remembers” which pebbles went in, and when.',
        '**Reservoir computing** uses the same trick. The “pond” is a big tangle of randomly connected artificial neurons that **nobody ever trains**. You pour your data in and learn only a simple rule for reading the ripples.',
        'Learning that rule is one quick calculation, so everything here learns **in the blink of an eye, right in your browser**. Each demo below does a job that’s normally given to big, slow-to-train AI.',
      ],
      detailed: [
        '**Reservoir computing** turns the usual approach to neural networks around. You build a large network of randomly connected neurons and **never train it**. You feed your data in and let it make ripples, and then train only a thin linear layer that reads those ripples out.',
        'Training that layer is a single least-squares solve, not hours of backpropagation, so everything here learns **in milliseconds, inside your browser**. No server, no GPU and no downloads are involved.',
        'Each demo below takes on a task that’s usually given to LSTMs or CNNs.',
      ],
    },
    diagram: {
      title: 'How a reservoir computer works',
      desc: 'An input signal enters a fixed, randomly connected network of neurons. A trained linear readout combines the neuron states into the output.',
      input: 'input',
      reservoir: 'reservoir',
      reservoirSub: 'random · fixed · never trained',
      readout: 'readout',
      readoutSub1: 'the only trained part:',
      readoutSub2: 'one linear solve',
      out: 'out',
    },
    usually: 'Usually',
    here: 'Here',
    open: 'Open demo →',
    cards: {
      chaos: {
        title: 'Forecasting chaos',
        simple: 'Weather-like systems are famously hard to predict. Watch a random network learn one in a third of a second, then keep imagining realistic new “weather” all by itself.',
        detailed: 'Predict the Lorenz “butterfly” system about 8 Lyapunov times ahead, then watch the network dream the attractor on its own.',
        usuallySimple: 'Big neural networks trained for minutes to hours',
        hereSimple: 'A random network plus one quick calculation',
        usuallyDetailed: 'LSTMs / GRUs trained with backpropagation through time',
        hereDetailed: '300 random neurons plus one ridge regression, about 0.3 s',
      },
      gestures: {
        title: 'Gesture recognition',
        simple: 'Draw a shape and it tells you what it is, often before you finish. Teach it a brand-new shape by drawing it three times.',
        detailed: 'Draw shapes with your mouse, finger or pen. Teach it a brand-new gesture from three examples and it guesses before you finish drawing.',
        usuallySimple: 'Large networks trained on thousands of drawings',
        hereSimple: 'Learns your new shape in under a second',
        usuallyDetailed: 'CNNs or RNNs trained on large labelled datasets',
        hereDetailed: '200 random neurons, retrained in milliseconds',
      },
      speech: {
        title: 'Spoken words',
        simple: 'Say “up”, “down”, “left” and “right” a few times each, then move a little square around with your voice.',
        detailed: 'Say “up”, “down”, “left” or “right” a few times, and then steer a token around a grid with your voice.',
        usuallySimple: 'Networks trained on over 100,000 voice clips',
        hereSimple: 'About five recordings of your own voice per word',
        usuallyDetailed: 'CNNs trained on datasets like Google Speech Commands (105,829 clips)',
        hereDetailed: 'About 5 of your own recordings per word, trained locally',
      },
      water: {
        title: 'A bucket of water',
        simple: 'Here the “brain” is a pretend tub of water. The ripples do the thinking; the computer only learns how to read them.',
        detailed: 'Use a simulated pond as the reservoir. Ripples from two “motors” are read at 48 points, and that’s enough to tell a sine wave from a square wave.',
        usuallySimple: 'A trained network does the thinking',
        hereSimple: 'Water does the thinking',
        usuallyDetailed: 'A trained network does the processing',
        hereDetailed: 'Physics does the processing; only the readout is learned',
      },
    },
    why: {
      title: 'Why does a random network work?',
      simple: [
        'Picture a big crowd listening to a story. Everyone reacts a little differently: some react to the last word, some still remember the previous sentence, some react to how two things go together. Ask the whole crowd how they feel and, between them, they hold a surprisingly detailed memory of the story.',
        'The reservoir is that crowd. We never teach the crowd anything. We only work out **how much to listen to each person**, and that is a simple weighted average the computer can find instantly.',
      ],
      detailed: [
        'Feed a signal into a big random recurrent network and every neuron responds with its own nonlinear mixture of the recent input. Some neurons react to the current value, some to what happened a few steps ago, some to products and combinations of the two. The network is a rich, fading *echo* of the past, which is why these are called **echo state networks**.',
        'Given enough of those different echoes, whatever you want to compute can usually be written as a **weighted sum** of them. Finding the weights is linear regression, which has a closed-form answer. There’s no gradient descent, no exploding gradients, no learning-rate schedules and no local minima.',
      ],
      knobsIntro: {
        simple: 'Every demo has a few knobs you can turn:',
        detailed: 'A few settings control the reservoir, and every demo lets you change them:',
      },
      knobs: {
        simple: [
          '**Spectral radius**: how long the crowd remembers. Too low and they forget at once; too high and they start chattering among themselves.',
          '**Input scaling**: how loudly we tell them the story.',
          '**Leak rate**: how quickly each person reacts. Slow for slow signals, fast for fast ones.',
          '**Ridge λ**: how careful we are not to trust any single person too much.',
        ],
        detailed: [
          '**Spectral radius**: how long echoes last. Near 0 the network forgets quickly. Above about 1 echoes can keep themselves going and turn chaotic.',
          '**Input scaling**: how hard the input pushes the neurons, from near-linear up to strongly saturated.',
          '**Leak rate**: how sluggish the neurons are, which matches the network to slow or fast signals.',
          '**Ridge λ**: how strongly the readout is kept simple, which guards against overfitting.',
        ],
      },
      physical: {
        simple: 'The “crowd” doesn’t even have to be a computer. People have used real buckets of water, beams of light on a chip and tiny magnets. The [water demo](#water) pretends to be one of those.',
        detailed: 'Because the reservoir is only “some rich dynamical system”, it doesn’t have to be software. People have built reservoirs from buckets of water, photonic chips, spintronic oscillators and soft robot bodies. The [water demo](#water) simulates the first of these.',
      },
    },
    weaker: {
      title: 'Where it’s weaker',
      simple: 'It isn’t magic. It’s great with signals that change over time and when there’s very little data, but it can’t write essays or recognise faces in photos like today’s big AI models. Its knobs still need a bit of tuning, too.',
      detailed: 'Reservoir computing isn’t a replacement for every kind of deep learning. It shines on **time series and dynamical systems**: small data, fast training and online learning. Its hyperparameters still need tuning. And when only part of a large system can be observed, networks trained with backpropagation often do better (Vlachas et al., 2020). Nobody is building a chatbot out of one.',
    },
    reading: {
      title: 'Further reading',
      notes: {
        jaeger: 'Reported a 2400× accuracy gain on Mackey–Glass prediction.',
        maass: 'The “liquid state machine”.',
        bucket: 'A real water tank solved XOR and told “zero” from “one”.',
        vlachas: 'With the full state observed, RC beat LSTM/GRU while needing far less training time.',
        luko: 'The best place to start if you want to build your own.',
      },
    },
  },

  chaos: {
    title: 'Forecasting chaos',
    lead: {
      simple: 'Chaotic systems are like the weather: tiny differences snowball until prediction becomes impossible. Here a random, untrained network watches one for a moment, learns to predict it in about a third of a second, and then keeps dreaming up realistic behaviour on its own.',
      detailed: 'A random, untrained network learns to predict a chaotic system in about a third of a second, then keeps generating its attractor on its own. LSTMs and other backprop-trained networks are the usual tool for this task.',
    },
    try: 'watch the orange line follow the blue one, then press **Perturb the dream** and see the butterfly shape come back.',
    systems: {
      lorenz: 'Lorenz (1963): a toy model of atmospheric convection, the original “butterfly effect”.',
      rossler: 'Rössler (1976): a spiral that now and then flings itself upward. Chaotic, but gentle.',
      mackeyGlass: 'Mackey–Glass (1977, τ = 17): a delay equation from blood-cell production, and a standard reservoir benchmark.',
    },
    stats: { valid: 'Valid forecast', linear: 'Linear model, no reservoir', samples: '({n} samples)' },
    // `dec` follows a decimal number; one/other follow whole numbers.
    units: {
      lt: { dec: 'Lyapunov times', one: 'Lyapunov time', other: 'Lyapunov times' },
      ltShort: 'LT',
      tu: { dec: 'time units', one: 'time unit', other: 'time units' },
      tuShort: 't',
    },
    controls: {
      system: 'Chaotic system',
      train: 'Train & forecast',
      newReservoir: 'New random reservoir',
      spectral: 'Spectral radius (memory / echo)',
      input: 'Input scaling',
      readout: 'Readout (the only trained part)',
      lambda: 'Ridge regularisation λ',
      steps: 'Training steps',
      squared: 'Squared readout features',
      squaredHint: 'Lets the linear readout see x² for half the neurons',
      compare: 'Compare with linear model',
      compareHint: 'Same training data and same ridge regression, but with no reservoir',
      dreaming: 'Dreaming',
      speed: 'Dream speed',
      speedUnit: '{v} steps/s',
      perturb: 'Perturb the dream',
      restart: 'Restart dream',
    },
    status: {
      generating: 'Generating data…',
      running: 'Running {steps} steps through {n} neurons and solving for the readout…',
      trained: 'Trained in {ms} ms on {samples} samples. The forecast is being revealed below.',
      kicked: 'Kicked off course. Watch whether it finds its way back to the attractor.',
      escaped: 'The dream escaped the attractor, so it was restarted. Some settings and systems make fragile models.',
      collapsed: 'The dream collapsed to a single point, so it was restarted. Some settings and systems make fragile models.',
    },
    cards: {
      forecast: 'Forecast vs. reality',
      forecastSub: 'left of the line: training data · right: the network predicting on its own',
      attractor: 'The attractor, dreamed',
      drag: 'drag to rotate',
      inside: 'Inside the reservoir',
      insideSub: '{rows} of the neurons, last {cols} steps',
    },
    legend: {
      truth: 'true trajectory',
      forecast: 'reservoir forecast',
      linear: 'linear model (no reservoir)',
      trueAttractor: 'true attractor',
      free: 'reservoir running freely',
      below: 'below',
      above: 'above the neuron’s own average',
    },
    canvas: {
      trainingEnds: 'training ends',
      accurate: 'still accurate up to here: {v} {unit}',
      accurateShort: 'accurate for {v} {unit}',
    },
    tooltip: {
      into: '{v} {unit} into the forecast',
      training: 'training data',
      true: 'true',
      reservoir: 'reservoir',
      linear: 'linear',
    },
    aria: {
      forecast: 'Forecast compared with the true trajectory',
      attractor: 'Three-dimensional view of the attractor; drag to rotate',
      raster: 'Activity of reservoir neurons over time',
    },
    explain: {
      summary: 'What am I looking at?',
      simple: [
        '**Top chart:** the blue line is what really happened and the orange line is the network’s guess. Left of the vertical line the network was watching and learning. Right of it, it’s on its own, building each guess on top of its own previous guesses.',
        'Chaos means small mistakes snowball, so every forecast drifts away in the end, just like weather forecasts get worse after a few days. The dashed line shows how long the guess stayed good.',
        '**Bottom left:** the famous butterfly shape. Even after its forecast has drifted, the network keeps tracing the right shape, because it learned *how the system behaves*, not just one path. Press **Perturb** to push it off and watch it find its way back.',
        '**Bottom right:** the network’s neurons flickering. Nobody trained them; they’re random. Only the final “reading” step was learned.',
        'The green dashed line is a simpler model without the random network. It gives up almost immediately.',
      ],
      detailed: [
        'The reservoir is a network of a few hundred randomly connected neurons with fixed weights. During training it is fed the true trajectory of a chaotic system, and a **single ridge regression** learns how to read the next point from the neurons’ states. That is the whole training process. There is no backpropagation and there are no epochs.',
        'Then the input is disconnected and each prediction is fed back in as the next input. The network now runs on its own and keeps generating the future. Chaos makes small errors grow exponentially. A **Lyapunov time** is how long an error takes to grow e-fold (≈2.7×). Weather forecasts lose accuracy after a few of them, so predicting about 8 Lyapunov times ahead from 4,000 samples is very good.',
        'Once the forecast has drifted from the true path, the reservoir keeps “dreaming” a trajectory that stays on the right attractor. It learned the system’s *climate* as well as its weather. Press **Perturb** to knock it off the attractor and watch it return.',
        'The linear model gets exactly the same data and training procedure. Its forecast falls apart almost immediately, which shows that the reservoir’s random nonlinear dynamics are what make the difference.',
      ],
    },
  },

  gestures: {
    title: 'Gesture recognition',
    lead: {
      simple: 'Draw a shape with your mouse, finger or pen. A random network turns your movement into a pattern of activity, a bit like a fingerprint, and a simple learned rule names it. Teach it a new shape by drawing it three times.',
      detailed: 'Draw with a mouse, finger or pen. A fixed random network turns your movement into a pattern of activity, and a linear readout names it. You can teach it new gestures from three examples.',
    },
    try: 'draw a circle or a star, then teach it something new, like a heart.',
    names: { circle: 'circle', triangle: 'triangle', square: 'square', check: 'check ✓', zigzag: 'zigzag', spiral: 'spiral', star: 'star', wave: 'wave', cross: 'cross ✕' },
    stats: { accuracy: 'Accuracy on unseen drawings', of: 'of {n}', examples: 'Training examples', yours: '({n} yours)' },
    drawHere: 'Draw here',
    clear: 'Clear',
    hint: 'Draw a shape here: circle, triangle, square, check, zigzag, spiral, star, wave or cross.',
    hintAgain: 'Draw a shape here, or teach it your own.',
    teachingHint: 'Teaching mode: draw “{name}”',
    guess: 'Its guess',
    drawSomething: 'Draw something…',
    notSure: '(not sure)',
    stillDrawing: '…still drawing',
    fingerprint: 'Reservoir fingerprint',
    fingerprintSub: '{rows} neurons × {cols} steps',
    fingerprintNote: 'The readout classifies this pattern of activity. It never looks at the picture itself.',
    appears: 'Appears when you draw',
    startStroke: 'start of stroke',
    end: 'end →',
    known: 'Gestures it knows',
    knownHint: 'Tap + to add more of your own examples to a gesture.',
    teachTitle: 'Teach a new gesture',
    namePlaceholder: 'Name, e.g. heart, arrow, M',
    nameAria: 'Name of the new gesture',
    teach: 'Teach it',
    done: 'Done',
    cancel: 'Cancel',
    resetGestures: 'Reset to built-in gestures',
    reservoirNote: 'Changing these builds a new random reservoir and retrains everything.',
    builtin: 'built-in',
    builtinPlus: { one: 'built-in + {n} of yours', other: 'built-in + {n} of yours' },
    yourExamples: { one: '{n} of your examples', other: '{n} of your examples' },
    addAria: 'Add examples of {name}',
    addTitle: 'Add examples',
    removeAria: 'Remove {name}',
    removeTitle: 'Remove',
    banner: {
      draw: 'Draw “{name}” on the canvas: example {k} of at least {min}.',
      got: { one: 'Got {n} example of “{name}”. Draw more for better accuracy, or press Done.', other: 'Got {n} examples of “{name}”. Draw more for better accuracy, or press Done.' },
    },
    status: {
      training: 'Training…',
      retrained: 'Retrained the readout on {n} examples in {ms} ms.',
      keepTwo: 'Keep at least two gestures, or there is nothing to choose between.',
      needName: 'Type a name for your gesture first.',
    },
    aria: { draw: 'Drawing area', heat: 'Reservoir activity while reading the gesture' },
    explain: {
      summary: 'How does it recognise a drawing?',
      simple: [
        'Your drawing is turned into 40 dots, and the dots are fed to the network one at a time: where the pen is, which way it’s moving and how sharply it’s turning.',
        'Like ripples in a pond, the neurons keep echoes of earlier dots. By the end, their pattern (the colourful “fingerprint”) describes your whole movement.',
        'The computer only learned which fingerprint goes with which name. Adding a new shape just means updating that list, which takes a fraction of a second.',
        'It has never seen human handwriting: the built-in shapes were learned from drawings the computer made up itself. Half-finished shapes were included too, which is why it can guess early.',
      ],
      detailed: [
        'Your stroke is resampled to {n} evenly spaced points. They are fed to the reservoir one at a time as position, direction of travel, how sharply it bends and a “pen lifted” flag. Like a pond after a stone drops in, the reservoir’s neurons keep echoing what came earlier, so by the end the state holds a fingerprint of the whole movement.',
        'The readout takes snapshots of that state at 25%, 50%, 75% and 100% of the gesture, plus its average, and a single ridge regression maps those snapshots to gesture names. Adding a new gesture means re-solving that one linear system, which takes well under a second. No gradient descent is involved.',
        'The built-in gestures are trained on drawings generated by the computer, so it has never seen your handwriting. It is tested on fresh generated drawings it has never seen. Partly drawn shapes are in the training data too, which is why it can guess before you finish.',
      ],
    },
  },

  speech: {
    title: 'Spoken word recognition',
    lead: {
      simple: 'Teach it a few words with your own voice, about five times each, and then steer the orange square by talking to it. Voice assistants learn from hundreds of thousands of clips; this learns from yours in under a second.',
      detailed: 'Keyword spotting usually takes a CNN trained on more than 100,000 clips. This uses a random reservoir trained on about five of your own recordings per word, inside your browser.',
    },
    try: 'press **Start microphone**, press **Record** next to each word and say it five times, then say “{left}”!',
    defaultWords: ['up', 'down', 'left', 'right'],
    moves: { up: 'up', down: 'down', left: 'left', right: 'right' },
    stats: { selfCheck: 'Self-check accuracy', leftOut: 'of {n}, each left out', recordings: 'Your recordings', suggested: 'of {n} suggested' },
    mic: '1 · Microphone',
    start: 'Start microphone',
    stop: 'Stop',
    sensitivity: 'Sensitivity (dB above background)',
    teachTitle: '2 · Teach it your words ({n} each)',
    teachHint: 'Press Record, then say the word several times with short pauses in between.',
    talkTitle: '3 · Talk to it',
    talkHint: 'Once every word has a few recordings, just say a word.',
    addWord: '+ Add word',
    newWord: 'word {n}',
    stopRecording: 'Stop recording',
    record: 'Record',
    recordMore: 'Record more',
    listening: 'Listening…',
    wordAria: 'Word {n}',
    recordingsAria: '{n} recordings',
    removeAria: 'Remove {name}',
    remember: 'Remember my recordings on this device',
    rememberHint: 'Stores sound features (not audio) in this browser only',
    forget: 'Forget all recordings',
    hears: 'What the microphone hears',
    hearsSub: 'last 3 seconds · low pitch at the bottom · orange bar = word detected',
    heard: 'It heard',
    voiceControl: 'Voice control',
    voiceGoal: 'Steer the orange square onto the green cell',
    goals: 'Goals reached: {n}',
    sayWords: 'Say “{up}”, “{down}”, “{left}” or “{right}”.',
    response: 'Reservoir response to the last word',
    responseSub: '{rows} neurons × time',
    sayOnce: 'Say a word once the model is trained',
    recordFirst: 'Record a few examples of each word first.',
    notSure: '(not sure)',
    banner: 'Say “{name}” ({k} of {n})…',
    got: 'Got it: “{name}” #{n}',
    trainingNow: 'Training…',
    recordSome: 'Record some examples first',
    status: {
      startFirst: 'Start the microphone first.',
      on: 'Microphone on ({khz} kHz). Speak normally; the background level adapts automatically.',
      off: 'Microphone off.',
      trained: 'Readout trained on {n} examples ({r} recordings plus stretched copies) in {ms} ms.',
      saveFailed: 'Could not save to this browser’s storage (it may be full or disabled).',
    },
    errors: {
      insecure: 'The microphone only works on a secure page: https:// or http://localhost. Open the hosted version, or run ./run.sh and use the localhost link.',
      unsupported: 'This browser lacks the audio features this demo needs (getUserMedia and AudioWorklet). Try a current Firefox, Chrome, Edge or Safari.',
      denied: 'Microphone permission was denied. Allow it in the address bar and try again.',
      failed: 'Could not start the microphone: {error}',
    },
    aria: { meter: 'Microphone level', spec: 'Live mel spectrogram of the microphone', heat: 'Reservoir activity for the last word', grid: 'Voice-controlled grid' },
    explain: {
      summary: 'How does this work, and what happens to my voice?',
      simple: [
        'The sound from your microphone is turned into a picture of which pitches are loud right now (the blue picture at the top). When you say a word, that picture is fed into the random network slice by slice.',
        'While the network listens, its activity works like a fingerprint of the word. The computer learns which fingerprint belongs to which word from your recordings, plus a few sped-up and slowed-down copies of them.',
        'It has only ever heard you, so it works best for your voice, in the same room and with the same microphone.',
      ],
      detailed: [
        'Every 10 ms the microphone signal is turned into 24 numbers that describe how much energy is in each frequency band, like the spectrogram above. A voice-activity detector cuts out each word, and the frames are fed one by one into a random reservoir of a few hundred neurons. The readout looks at the reservoir’s state at five moments during the word plus its average, and is trained with one ridge regression on your recordings. Each recording is also time-stretched into a few slightly faster and slower versions.',
        'Commercial keyword spotters are deep CNNs trained on tens of thousands of clips from thousands of speakers. This model has only heard you, about five times per word, so it works best in the same room, with the same mic and voice. A different person will probably confuse it. That is the trade-off: almost no data, almost no training time.',
      ],
      privacy: '**Privacy:** the audio is processed inside this page and never leaves your device. No audio is stored. If you tick “remember”, only the 24-number summaries are saved, in this browser’s local storage. The microphone turns off when you leave this tab.',
    },
  },

  water: {
    title: 'A bucket of water',
    lead: {
      simple: 'What if the “brain” were just a tub of water? Two paddles make waves that follow a signal, and the computer only learns how to read the ripples at 48 spots. That’s enough to tell a smooth wave from a choppy one.',
      detailed: 'Any system with rich enough dynamics can serve as the reservoir. Here a simulated pond does the computing, and the only thing trained is how to read 48 points on its surface.',
    },
    try: 'untick **Nonlinear camera** and watch the orange line get confused, then tick it again.',
    stats: { accuracy: 'Accuracy, all samples', settled: 'Accuracy after 1.5 periods', recall: 'Recall quality R²', forD: 'for d = {d}', weights: '({p} probes{x} + bias)' },
    task: 'Task',
    tasks: { shape: 'Tell a sine wave from a square wave', memory: 'Remember the past (recall the input from d steps ago)' },
    camera: 'Nonlinear camera',
    cameraHint: 'Sees brightness ≈ height², averaged over its exposure, as well as the height itself',
    delay: 'Delay d',
    delayUnit: { one: '{n} step', other: '{n} steps' },
    bucket: 'The bucket',
    damping: 'Damping (how quickly ripples die)',
    probes: 'Probe points',
    live: 'Live run',
    speed: 'Simulation speed',
    speedUnit: '{v} samples/s',
    pause: 'Pause',
    resume: 'Resume',
    splash: 'Splash!',
    pond: 'The pond',
    pondSub: 'motors on the left · probe points shown as rings',
    motors: 'motors',
    readout: 'Live readout',
    readoutSub: 'newest on the right',
    curve: 'How long does the water remember?',
    curveSub: 'R² of recalling the input from d steps ago',
    legend: { input: 'input signal', answer: 'right answer (up = square)', readout: 'readout', past: 'input d steps ago (to recall)' },
    status: {
      making: 'Making waves…',
      trained: '{samples} input samples sent through {cells} cells of water, readout solved in {ms} ms. Now testing on a fresh signal.',
    },
    aria: { pond: 'Simulated water surface with motors and probe points', trace: 'Input signal, correct answer and the readout over time', curve: 'How well the past can be recalled, by delay' },
    explain: {
      summary: 'Why would water compute anything?',
      simple: [
        'Two paddles (the blue dots) push the water up and down, following the signal. The ripples spread out, bounce off the walls and overlap, so the surface becomes a kind of memory of what the signal did a moment ago.',
        'The little rings are 48 measuring points, like a camera looking at the water. The computer only learns how to combine those 48 readings into an answer. The water itself is never trained.',
        'To the water, a smooth (sine) wave and a choppy (square) wave look very alike. A real camera sees light bending through the ripples, which isn’t a simple straight-line relationship, and that small twist is enough to tell them apart. Untick the camera option and it gets confused.',
        'Scientists really did this in 2003, with a tank of water, LEGO motors and a webcam.',
      ],
      detailed: [
        'Two “motors” on the left push the water up and down following the input signal. Ripples spread out, bounce off the walls and overlap. At any moment the surface holds a mixture of what the motors did over the last few moments, so it is a physical memory of the input’s recent history.',
        'The probe points are the camera. A linear readout, trained with one ridge regression, combines their readings into the answer. Nothing about the water is trained, and the water doesn’t “know” anything about sine or square waves.',
        'Ripples in this simulation obey a linear wave equation, so from the height alone a linear readout can only produce another linear filter of the input. That is fine for remembering the past, but a filtered sine is still a sine, so it can never settle on a steady “this is a square” answer. Turn the nonlinear camera off and the readout swings around wildly. A real camera looking at water through a light source sees brightness that depends nonlinearly on the surface, and it averages light over its exposure. That one nonlinearity is enough for the readout to tell the shapes apart.',
        'Fernando & Sojakka (2003) did this for real: a tank of water on an overhead projector, LEGO motors and a webcam. It solved XOR and told the spoken words “zero” and “one” apart.',
      ],
    },
  },
};
