// Slovenské texty celej aplikácie. Značky v texte: **tučné**, *kurzíva*,
// [odkaz](url). {zástupné symboly} dopĺňa t(); množné číslo má tvary
// one (1), few (2 – 4) a other (0, 5 a viac).

export default {
  meta: {
    title: 'Rezervoárové počítanie – interaktívne ukážky',
    description: 'Interaktívne ukážky rezervoárového počítania: predpovedaj chaos, rozpoznávaj gestá a hovorené slová a počítaj so simulovaným vedrom vody. Všetko sa trénuje za milisekundy priamo v prehliadači.',
  },

  nav: {
    home: 'Rezervoárové počítanie, úvodná stránka',
    brand: 'Rezervoárové počítanie',
    demos: 'Ukážky',
    intro: 'Úvod',
    chaos: 'Chaos',
    gestures: 'Gestá',
    speech: 'Reč',
    water: 'Voda',
    theme: 'Farebná téma: {theme} (kliknutím zmeníš)',
    themes: { auto: 'automatická', light: 'svetlá', dark: 'tmavá' },
    language: 'Jazyk',
  },

  common: {
    level: { label: 'Vysvetlenie', simple: 'Jednoducho', detailed: 'Podrobne' },
    tryIt: 'Vyskúšaj:',
    reset: '↺ Obnoviť nastavenia',
    resetDone: 'Nastavenia sú opäť na predvolených hodnotách.',
    trainingTime: 'Čas trénovania',
    trainedWeights: 'Natrénované váhy',
    neurons: 'Počet neurónov',
    spectralRadius: 'Spektrálny polomer',
    leak: 'Miera úniku',
    reservoir: 'Rezervoár',
    ms: 'ms',
    s: 's',
    older: '← staršie',
    now: 'teraz →',
    loadFailed: 'Prepáč, túto ukážku sa nepodarilo načítať: {error}',
    footer: 'Všetko beží priamo v tvojom prehliadači a nič sa nikam neodosiela. Slobodný softvér pod licenciou GNU GPL v3.',
    source: 'Zdrojový kód',
  },

  intro: {
    title: 'Strojové učenie bez trénovania siete',
    hero: {
      simple: [
        'Hoď do jazierka pár kamienkov a sleduj, ako sa vlnky šíria, odrážajú a miešajú. Keď sa na hladinu pozrieš o chvíľu neskôr, stále si „pamätá“, ktoré kamienky do nej dopadli a kedy.',
        '**Rezervoárové počítanie** (reservoir computing) využíva presne tento trik. „Jazierkom“ je tu veľká spleť náhodne poprepájaných umelých neurónov, ktoré **nikto nikdy netrénuje**. Pustíš do nich svoje dáta a naučíš sa iba jednoduché pravidlo, ako vlnky čítať.',
        'Naučiť sa to pravidlo je jediný rýchly výpočet, takže všetko tu sa učí **za okamih, priamo v tvojom prehliadači**. Každá ukážka nižšie zvláda úlohu, ktorú zvyčajne dostáva veľká a pomaly trénovaná umelá inteligencia.',
      ],
      detailed: [
        '**Rezervoárové počítanie** (reservoir computing) obracia bežný prístup k neurónovým sieťam naruby. Postavíš veľkú sieť náhodne poprepájaných neurónov a **nikdy ju netrénuješ**. Pustíš do nej dáta, necháš ju „vlniť sa“ a natrénuješ iba tenkú lineárnu vrstvu, ktorá tieto vlny číta.',
        'Natrénovať túto vrstvu znamená vyriešiť jednu úlohu metódou najmenších štvorcov, nie hodiny spätného šírenia chyby (backpropagation), takže všetko sa tu učí **za milisekundy, priamo v prehliadači**. Žiadny server, žiadna grafická karta, nič na sťahovanie.',
        'Každá ukážka nižšie rieši úlohu, na ktorú sa zvyčajne používajú siete LSTM alebo CNN.',
      ],
    },
    diagram: {
      title: 'Ako funguje rezervoárový počítač',
      desc: 'Vstupný signál prichádza do pevnej, náhodne poprepájanej siete neurónov. Natrénovaná lineárna výstupná vrstva skladá stavy neurónov do výstupu.',
      input: 'vstup',
      reservoir: 'rezervoár',
      reservoirSub: 'náhodný · pevný · nikdy netrénovaný',
      readout: 'výstupná vrstva',
      readoutSub1: 'jediná trénovaná časť:',
      readoutSub2: 'jeden lineárny výpočet',
      out: 'výstup',
    },
    usually: 'Zvyčajne',
    here: 'Tu',
    open: 'Otvoriť ukážku →',
    cards: {
      chaos: {
        title: 'Predpovedanie chaosu',
        simple: 'Systémy podobné počasiu sa predpovedajú povestne ťažko. Pozri sa, ako sa náhodná sieť jeden z nich naučí za tretinu sekundy a potom si sama vymýšľa ďalšie realistické „počasie“.',
        detailed: 'Predpovedz Lorenzov „motýlí“ systém zhruba 8 Ljapunovových časov dopredu a potom sleduj, ako sieť sama „sníva“ jeho atraktor.',
        usuallySimple: 'Veľké neurónové siete trénované minúty až hodiny',
        hereSimple: 'Náhodná sieť a jeden rýchly výpočet',
        usuallyDetailed: 'Siete LSTM / GRU trénované spätným šírením chyby v čase',
        hereDetailed: '300 náhodných neurónov a jedna hrebeňová regresia, asi 0,3 s',
      },
      gestures: {
        title: 'Rozpoznávanie gest',
        simple: 'Nakresli tvar a sieť ti povie, čo to je, často ešte predtým, než ho dokreslíš. Úplne nový tvar ju naučíš tak, že ho trikrát nakreslíš.',
        detailed: 'Kresli tvary myšou, prstom alebo perom. Nové gesto ju naučíš z troch príkladov a háda ešte skôr, než dokreslíš.',
        usuallySimple: 'Veľké siete trénované na tisícoch kresieb',
        hereSimple: 'Nový tvar sa naučí za menej než sekundu',
        usuallyDetailed: 'Siete CNN alebo RNN trénované na veľkých označených dátach',
        hereDetailed: '200 náhodných neurónov, pretrénovanie za milisekundy',
      },
      speech: {
        title: 'Hovorené slová',
        simple: 'Povedz niekoľkokrát „hore“, „dole“, „vľavo“ a „vpravo“ a potom hlasom posúvaj štvorček po mriežke.',
        detailed: 'Niekoľkokrát povedz „hore“, „dole“, „vľavo“ alebo „vpravo“ a potom hlasom riaď značku po mriežke.',
        usuallySimple: 'Siete trénované na viac než 100 000 nahrávkach hlasu',
        hereSimple: 'Zhruba päť nahrávok tvojho hlasu na každé slovo',
        usuallyDetailed: 'Siete CNN trénované na dátach ako Google Speech Commands (105 829 nahrávok)',
        hereDetailed: 'Asi 5 tvojich vlastných nahrávok na slovo, trénované lokálne',
      },
      water: {
        title: 'Vedro vody',
        simple: '„Mozgom“ je tu vymyslená vaňa s vodou. Rozmýšľajú vlnky, počítač sa učí iba to, ako ich čítať.',
        detailed: 'Rezervoárom je simulované jazierko. Vlny z dvoch „motorčekov“ sa čítajú v 48 bodoch a to stačí na rozlíšenie sínusovej vlny od obdĺžnikovej.',
        usuallySimple: 'Rozmýšľa natrénovaná sieť',
        hereSimple: 'Rozmýšľa voda',
        usuallyDetailed: 'Spracovanie robí natrénovaná sieť',
        hereDetailed: 'Spracovanie robí fyzika, učí sa iba výstupná vrstva',
      },
    },
    why: {
      title: 'Prečo funguje náhodná sieť?',
      simple: [
        'Predstav si veľký dav, ktorý počúva príbeh. Každý reaguje trochu inak: niekto na posledné slovo, niekto si ešte pamätá predošlú vetu, iný si všíma, ako spolu dve veci súvisia. Keď sa opýtaš celého davu, ako sa cíti, spolu si z príbehu pamätajú prekvapivo veľa podrobností.',
        'Rezervoár je presne taký dav. Dav nikdy nič neučíme. Zisťujeme iba to, **koho a ako veľmi treba počúvať**, a to je obyčajný vážený priemer, ktorý počítač nájde okamžite.',
      ],
      detailed: [
        'Keď pustíš signál do veľkej náhodnej rekurentnej siete, každý neurón odpovie vlastnou nelineárnou zmesou nedávneho vstupu. Niektoré neuróny reagujú na aktuálnu hodnotu, iné na to, čo sa stalo pred pár krokmi, ďalšie na súčiny a kombinácie oboch. Sieť je bohatou, postupne doznievajúcou *ozvenou* minulosti, preto sa takým sieťam hovorí **siete s ozvenovým stavom** (echo state networks).',
        'Ak je takých ozvien dosť, to, čo chceš vypočítať, sa dá zvyčajne zapísať ako ich **vážený súčet**. Nájsť váhy je lineárna regresia, ktorá má riešenie v uzavretom tvare. Žiadny gradientný zostup, žiadne explodujúce gradienty, žiadne ladenie rýchlosti učenia a žiadne lokálne minimá.',
      ],
      knobsIntro: {
        simple: 'Každá ukážka má zopár gombíkov, ktorými môžeš krútiť:',
        detailed: 'Rezervoár riadi niekoľko nastavení a v každej ukážke ich môžeš meniť:',
      },
      knobs: {
        simple: [
          '**Spektrálny polomer**: ako dlho si dav pamätá. Keď je príliš nízky, hneď zabudnú, keď je príliš vysoký, začnú sa rozprávať medzi sebou.',
          '**Škálovanie vstupu**: ako nahlas im príbeh rozprávame.',
          '**Miera úniku**: ako rýchlo každý reaguje. Pomaly na pomalé signály, rýchlo na rýchle.',
          '**Regularizácia λ**: ako veľmi si dávame pozor, aby sme nikomu neverili priveľa.',
        ],
        detailed: [
          '**Spektrálny polomer**: ako dlho ozveny trvajú. Blízko 0 sieť rýchlo zabúda. Zhruba nad 1 sa ozveny dokážu samy udržiavať a sieť sa stáva chaotickou.',
          '**Škálovanie vstupu**: ako silno vstup tlačí na neuróny, od takmer lineárneho správania až po silné nasýtenie.',
          '**Miera úniku**: ako pomaly neuróny reagujú, čím sa sieť prispôsobí pomalým alebo rýchlym signálom.',
          '**Regularizácia λ** (hrebeňová regresia): ako silno udržiavame výstupnú vrstvu jednoduchú, čo ju chráni pred preučením.',
        ],
      },
      physical: {
        simple: '„Dav“ ani nemusí byť počítač. Ľudia už použili skutočné vedrá s vodou, lúče svetla na čipe aj drobné magnetky. [Ukážka s vodou](#water) jeden taký napodobňuje.',
        detailed: 'Keďže rezervoár je len „nejaký bohatý dynamický systém“, nemusí byť vôbec softvérom. Rezervoáre už postavili z vedier s vodou, fotonických čipov, spintronických oscilátorov aj z mäkkých robotických tiel. [Ukážka s vodou](#water) simuluje ten prvý.',
      },
    },
    weaker: {
      title: 'V čom zaostáva',
      simple: 'Nie je to žiadna mágia. Výborne si poradí so signálmi, ktoré sa menia v čase, a aj vtedy, keď je dát veľmi málo. Nenapíše však sloh ani nespozná tváre na fotkách ako dnešné veľké modely umelej inteligencie. A aj jeho gombíky treba trochu doladiť.',
      detailed: 'Rezervoárové počítanie nenahradí každý druh hlbokého učenia. Vyniká pri **časových radoch a dynamických systémoch**: málo dát, rýchle trénovanie a učenie za behu. Hyperparametre treba stále ladiť. A keď vidno len časť veľkého systému, siete trénované spätným šírením chyby často dopadnú lepšie (Vlachas a kol., 2020). Chatbota z neho nikto nestavia.',
    },
    reading: {
      title: 'Na ďalšie čítanie',
      notes: {
        jaeger: 'Uvádza 2400-násobné zlepšenie presnosti pri predpovedi Mackeyho–Glassovej rovnice.',
        maass: '„Stroj s tekutým stavom“ (liquid state machine).',
        bucket: 'Skutočná nádrž s vodou vyriešila XOR a rozlíšila slová „zero“ a „one“.',
        vlachas: 'Pri pozorovaní celého stavu prekonalo RC siete LSTM/GRU a potrebovalo oveľa menej času na trénovanie.',
        luko: 'Najlepší začiatok, ak si chceš postaviť vlastný.',
      },
    },
  },

  chaos: {
    title: 'Predpovedanie chaosu',
    lead: {
      simple: 'Chaotické systémy sú ako počasie: drobné rozdiely sa nabaľujú, až sa už predpovedať nedá. Náhodná, netrénovaná sieť sa tu na jeden taký systém chvíľu pozerá, asi za tretinu sekundy sa ho naučí predpovedať a potom si sama ďalej sníva jeho realistické správanie.',
      detailed: 'Náhodná, netrénovaná sieť sa asi za tretinu sekundy naučí predpovedať chaotický systém a potom sama ďalej generuje jeho atraktor. Bežne sa na to používajú siete LSTM a iné siete trénované spätným šírením chyby.',
    },
    try: 'sleduj, ako oranžová čiara kopíruje modrú, potom stlač **Vyrušiť sen** a pozri sa, ako sa motýlí tvar vráti.',
    systems: {
      lorenz: 'Lorenz (1963): zjednodušený model prúdenia v atmosfére, pôvodný „motýlí efekt“.',
      rossler: 'Rössler (1976): špirála, ktorá sa raz za čas vymrští nahor. Chaotická, ale pokojná.',
      mackeyGlass: 'Mackey–Glass (1977, τ = 17): rovnica s oneskorením z modelu tvorby krviniek a klasický test pre rezervoáre.',
    },
    stats: { valid: 'Platná predpoveď', linear: 'Lineárny model bez rezervoára', samples: '({n} vzoriek)' },
    // `dec` nasleduje po desatinnom čísle (8,2 Ljapunovovho času);
    // one/few/other po celom čísle (1 čas, 3 časy, 25 časov).
    units: {
      lt: { dec: 'Ljapunovovho času', one: 'Ljapunovov čas', few: 'Ljapunovove časy', other: 'Ljapunovových časov' },
      ltShort: 'LČ',
      tu: { dec: 'časovej jednotky', one: 'časová jednotka', few: 'časové jednotky', other: 'časových jednotiek' },
      tuShort: 't',
    },
    controls: {
      system: 'Chaotický systém',
      train: 'Natrénovať a predpovedať',
      newReservoir: 'Nový náhodný rezervoár',
      spectral: 'Spektrálny polomer (pamäť / ozvena)',
      input: 'Škálovanie vstupu',
      readout: 'Výstupná vrstva (jediná trénovaná časť)',
      lambda: 'Regularizácia λ (hrebeňová)',
      steps: 'Počet trénovacích krokov',
      squared: 'Druhé mocniny na výstupe',
      squaredHint: 'Lineárna výstupná vrstva vidí pri polovici neurónov aj x²',
      compare: 'Porovnať s lineárnym modelom',
      compareHint: 'Rovnaké trénovacie dáta aj rovnaká hrebeňová regresia, ale bez rezervoára',
      dreaming: 'Snívanie',
      speed: 'Rýchlosť sna',
      speedUnit: '{v} krokov/s',
      perturb: 'Vyrušiť sen',
      restart: 'Spustiť sen odznova',
    },
    status: {
      generating: 'Generujem dáta…',
      running: 'Púšťam {steps} krokov cez {n} neurónov a počítam výstupnú vrstvu…',
      trained: 'Natrénované za {ms} ms na {samples} vzorkách. Predpoveď sa práve vykresľuje nižšie.',
      kicked: 'Sen je vychýlený z kurzu. Sleduj, či nájde cestu späť na atraktor.',
      escaped: 'Sen ušiel z atraktora, preto sa spustil odznova. Niektoré nastavenia a systémy vedú ku krehkým modelom.',
      collapsed: 'Sen sa zrútil do jediného bodu, preto sa spustil odznova. Niektoré nastavenia a systémy vedú ku krehkým modelom.',
    },
    cards: {
      forecast: 'Predpoveď a skutočnosť',
      forecastSub: 'vľavo od čiary: trénovacie dáta · vpravo: sieť predpovedá sama',
      attractor: 'Atraktor zo sna',
      drag: 'otáčaj ťahaním',
      inside: 'Vnútri rezervoára',
      insideSub: '{rows} neurónov, posledných {cols} krokov',
    },
    legend: {
      truth: 'skutočná trajektória',
      forecast: 'predpoveď rezervoára',
      linear: 'lineárny model (bez rezervoára)',
      trueAttractor: 'skutočný atraktor',
      free: 'voľne bežiaci rezervoár',
      below: 'pod',
      above: 'nad vlastným priemerom neurónu',
    },
    canvas: {
      trainingEnds: 'koniec trénovania',
      accurate: 'presná až potiaľto: {v} {unit}',
      accurateShort: 'presná {v} {unit}',
    },
    tooltip: {
      into: '{v} {unit} od začiatku predpovede',
      training: 'trénovacie dáta',
      true: 'skutočnosť',
      reservoir: 'rezervoár',
      linear: 'lineárny',
    },
    aria: {
      forecast: 'Predpoveď v porovnaní so skutočnou trajektóriou',
      attractor: 'Trojrozmerný pohľad na atraktor, otáčaj ťahaním',
      raster: 'Aktivita neurónov rezervoára v čase',
    },
    explain: {
      summary: 'Na čo sa to pozerám?',
      simple: [
        '**Horný graf:** modrá čiara ukazuje, čo sa naozaj stalo, a oranžová je odhad siete. Vľavo od zvislej čiary sieť pozorovala a učila sa. Vpravo od nej už je sama a každý ďalší odhad stavia na svojich predchádzajúcich odhadoch.',
        'Chaos znamená, že sa drobné chyby nabaľujú ako snehová guľa, takže každá predpoveď sa časom so skutočnosťou rozíde, presne ako predpoveď počasia na viac dní dopredu. Prerušovaná čiara ukazuje, ako dlho bol odhad dobrý.',
        '**Vľavo dole:** slávny motýlí tvar. Aj keď sa predpoveď už rozišla, sieť stále kreslí správny tvar, pretože sa naučila, *ako sa systém správa*, a nie iba jednu konkrétnu cestu. Stlač **Vyrušiť sen**, vychýľ ju a sleduj, ako nájde cestu späť.',
        '**Vpravo dole:** blikajúce neuróny siete. Nikto ich netrénoval, sú náhodné. Naučený je iba posledný krok, ktorý ich „číta“.',
        'Zelená prerušovaná čiara je jednoduchší model bez náhodnej siete. Vzdá sa takmer okamžite.',
      ],
      detailed: [
        'Rezervoár je sieť niekoľkých stoviek náhodne poprepájaných neurónov s pevnými váhami. Počas trénovania do nej púšťame skutočnú trajektóriu chaotického systému a **jediná hrebeňová regresia** sa naučí zo stavov neurónov odčítať ďalší bod. To je celé trénovanie. Žiadne spätné šírenie chyby, žiadne epochy.',
        'Potom sa vstup odpojí a každá predpoveď sa vracia späť ako ďalší vstup. Sieť teraz beží sama a generuje budúcnosť. Chaos spôsobuje, že malé chyby rastú exponenciálne. **Ljapunovov čas** je doba, za ktorú chyba narastie e-krát (≈ 2,7×). Predpovede počasia strácajú presnosť už po niekoľkých takých časoch, takže predpoveď zhruba 8 Ljapunovových časov dopredu zo 4 000 vzoriek je veľmi dobrý výsledok.',
        'Keď sa predpoveď odchýli od skutočnej trajektórie, rezervoár ďalej „sníva“ trajektóriu, ktorá zostáva na správnom atraktore. Naučil sa *podnebie* systému, nielen jeho počasie. Stlač **Vyrušiť sen**, vychýľ ho z atraktora a sleduj, ako sa vráti.',
        'Lineárny model dostane presne tie isté dáta a rovnaký postup trénovania. Jeho predpoveď sa rozpadne takmer okamžite, čo ukazuje, že rozdiel robí práve náhodná nelineárna dynamika rezervoára.',
      ],
    },
  },

  gestures: {
    title: 'Rozpoznávanie gest',
    lead: {
      simple: 'Nakresli tvar myšou, prstom alebo perom. Náhodná sieť premení tvoj pohyb na vzor aktivity, niečo ako odtlačok prsta, a jednoduché naučené pravidlo mu dá meno. Nový tvar ju naučíš tak, že ho trikrát nakreslíš.',
      detailed: 'Kresli myšou, prstom alebo perom. Pevná náhodná sieť premení tvoj pohyb na vzor aktivity a lineárna výstupná vrstva ho pomenuje. Nové gestá ju naučíš z troch príkladov.',
    },
    try: 'nakresli kruh alebo hviezdu a potom ju nauč niečo nové, napríklad srdce.',
    names: { circle: 'kruh', triangle: 'trojuholník', square: 'štvorec', check: 'fajka ✓', zigzag: 'cikcak', spiral: 'špirála', star: 'hviezda', wave: 'vlnovka', cross: 'krížik ✕' },
    stats: { accuracy: 'Presnosť na neznámych kresbách', of: 'z {n}', examples: 'Trénovacie príklady', yours: '({n} tvojich)' },
    drawHere: 'Kresli sem',
    clear: 'Vymazať',
    hint: 'Nakresli sem tvar: kruh, trojuholník, štvorec, fajku, cikcak, špirálu, hviezdu, vlnovku alebo krížik.',
    hintAgain: 'Nakresli sem tvar alebo ju nauč vlastný.',
    teachingHint: 'Režim učenia: nakresli „{name}“',
    guess: 'Jej odhad',
    drawSomething: 'Nakresli niečo…',
    notSure: '(neistý odhad)',
    stillDrawing: '…ešte kreslíš',
    fingerprint: 'Odtlačok rezervoára',
    fingerprintSub: '{rows} neurónov × {cols} krokov',
    fingerprintNote: 'Výstupná vrstva klasifikuje tento vzor aktivity. Na samotný obrázok sa nikdy nepozerá.',
    appears: 'Objaví sa, keď začneš kresliť',
    startStroke: 'začiatok ťahu',
    end: 'koniec →',
    known: 'Gestá, ktoré pozná',
    knownHint: 'Klikni na +, ak chceš ku gestu pridať vlastné príklady.',
    teachTitle: 'Nauč ju nové gesto',
    namePlaceholder: 'Názov, napr. srdce, šípka, M',
    nameAria: 'Názov nového gesta',
    teach: 'Naučiť',
    done: 'Hotovo',
    cancel: 'Zrušiť',
    resetGestures: 'Obnoviť vstavané gestá',
    reservoirNote: 'Zmena týchto hodnôt vytvorí nový náhodný rezervoár a všetko pretrénuje.',
    builtin: 'vstavané',
    builtinPlus: { one: 'vstavané + {n} tvoj', few: 'vstavané + {n} tvoje', other: 'vstavané + {n} tvojich' },
    yourExamples: { one: '{n} tvoj príklad', few: '{n} tvoje príklady', other: '{n} tvojich príkladov' },
    addAria: 'Pridať príklady gesta {name}',
    addTitle: 'Pridať príklady',
    removeAria: 'Odstrániť gesto {name}',
    removeTitle: 'Odstrániť',
    banner: {
      draw: 'Nakresli na plochu „{name}“: príklad {k} z aspoň {min}.',
      got: {
        one: 'Mám {n} príklad gesta „{name}“. Pre vyššiu presnosť nakresli ďalšie alebo stlač Hotovo.',
        few: 'Mám {n} príklady gesta „{name}“. Pre vyššiu presnosť nakresli ďalšie alebo stlač Hotovo.',
        other: 'Mám {n} príkladov gesta „{name}“. Pre vyššiu presnosť nakresli ďalšie alebo stlač Hotovo.',
      },
    },
    status: {
      training: 'Trénujem…',
      retrained: 'Výstupná vrstva je pretrénovaná na {n} príkladoch za {ms} ms.',
      keepTwo: 'Nechaj aspoň dve gestá, inak nie je z čoho vyberať.',
      needName: 'Najprv napíš názov gesta.',
    },
    aria: { draw: 'Plocha na kreslenie', heat: 'Aktivita rezervoára pri čítaní gesta' },
    explain: {
      summary: 'Ako spozná kresbu?',
      simple: [
        'Tvoja kresba sa premení na 40 bodiek a tie idú do siete jedna po druhej: kde je pero, ktorým smerom sa hýbe a ako prudko zatáča.',
        'Neuróny si, podobne ako vlnky na jazierku, uchovávajú ozveny predchádzajúcich bodiek. Na konci ich vzor (farebný „odtlačok“) opisuje celý tvoj pohyb.',
        'Počítač sa naučil iba to, ktorý odtlačok patrí ku ktorému názvu. Pridať nový tvar znamená len doplniť tento zoznam a trvá to zlomok sekundy.',
        'Ľudský rukopis nikdy nevidela: vstavané tvary sa naučila z kresieb, ktoré si počítač sám vymyslel. Boli medzi nimi aj nedokreslené tvary, preto dokáže hádať skôr, než dokreslíš.',
      ],
      detailed: [
        'Tvoj ťah sa prevzorkuje na {n} rovnomerne rozložených bodov. Do rezervoára idú jeden po druhom ako poloha, smer pohybu, ostrosť zatáčania a príznak „pero zdvihnuté“. Ako jazierko po dopade kameňa, aj neuróny rezervoára ďalej doznievajú tým, čo prišlo predtým, takže na konci stav obsahuje odtlačok celého pohybu.',
        'Výstupná vrstva si zoberie snímky tohto stavu v 25 %, 50 %, 75 % a 100 % gesta a k tomu jeho priemer a jediná hrebeňová regresia priradí týmto snímkam názvy gest. Pridať nové gesto znamená znova vyriešiť tento jeden lineárny systém, čo trvá oveľa menej než sekundu. Žiadny gradientný zostup.',
        'Vstavané gestá sú natrénované na kresbách, ktoré vygeneroval počítač, takže tvoj rukopis nikdy nevidela. Testuje sa na nových vygenerovaných kresbách, ktoré tiež nikdy nevidela. V trénovacích dátach sú aj čiastočne nakreslené tvary, preto dokáže hádať ešte predtým, než dokreslíš.',
      ],
    },
  },

  speech: {
    title: 'Rozpoznávanie hovorených slov',
    lead: {
      simple: 'Nauč ju pár slov vlastným hlasom, každé asi päťkrát, a potom riaď oranžový štvorček hovorením. Hlasoví asistenti sa učia zo stoviek tisíc nahrávok, táto sieť sa naučí z tvojich za menej než sekundu.',
      detailed: 'Rozpoznávanie kľúčových slov si bežne vyžaduje sieť CNN natrénovanú na viac než 100 000 nahrávkach. Tu stačí náhodný rezervoár natrénovaný na zhruba piatich tvojich nahrávkach na slovo, priamo v prehliadači.',
    },
    try: 'stlač **Zapnúť mikrofón**, pri každom slove stlač **Nahrať** a povedz ho päťkrát, potom povedz „{left}“!',
    defaultWords: ['hore', 'dole', 'vľavo', 'vpravo'],
    moves: { up: 'hore', down: 'dole', left: 'vľavo', right: 'vpravo' },
    stats: { selfCheck: 'Presnosť pri samokontrole', leftOut: 'z {n}, vždy jedna vynechaná', recordings: 'Tvoje nahrávky', suggested: 'z {n} odporúčaných' },
    mic: '1 · Mikrofón',
    start: 'Zapnúť mikrofón',
    stop: 'Vypnúť',
    sensitivity: 'Citlivosť (dB nad pozadím)',
    teachTitle: '2 · Nauč ju svoje slová (každé {n}×)',
    teachHint: 'Stlač Nahrať a povedz slovo niekoľkokrát s krátkymi pauzami.',
    talkTitle: '3 · Prihovor sa jej',
    talkHint: 'Keď má každé slovo pár nahrávok, stačí povedať slovo.',
    addWord: '+ Pridať slovo',
    newWord: 'slovo {n}',
    stopRecording: 'Zastaviť nahrávanie',
    record: 'Nahrať',
    recordMore: 'Nahrať ďalšie',
    listening: 'Počúvam…',
    wordAria: 'Slovo {n}',
    recordingsAria: 'Počet nahrávok: {n}',
    removeAria: 'Odstrániť slovo {name}',
    remember: 'Zapamätať si moje nahrávky na tomto zariadení',
    rememberHint: 'Ukladá iba zvukové príznaky (nie zvuk), a to len v tomto prehliadači',
    forget: 'Zabudnúť všetky nahrávky',
    hears: 'Čo počuje mikrofón',
    hearsSub: 'posledné 3 sekundy · nízke tóny dole · oranžový pruh = zachytené slovo',
    heard: 'Rozpoznané slovo',
    voiceControl: 'Ovládanie hlasom',
    voiceGoal: 'Dostaň oranžový štvorček na zelené políčko',
    goals: 'Dosiahnuté ciele: {n}',
    sayWords: 'Povedz „{up}“, „{down}“, „{left}“ alebo „{right}“.',
    response: 'Odozva rezervoára na posledné slovo',
    responseSub: '{rows} neurónov × čas',
    sayOnce: 'Keď bude model natrénovaný, povedz nejaké slovo',
    recordFirst: 'Najprv nahraj pár príkladov každého slova.',
    notSure: '(neistý odhad)',
    banner: 'Povedz „{name}“ ({k} z {n})…',
    got: 'Mám to: „{name}“ č. {n}',
    trainingNow: 'Trénujem…',
    recordSome: 'Najprv nahraj nejaké príklady',
    status: {
      startFirst: 'Najprv zapni mikrofón.',
      on: 'Mikrofón je zapnutý ({khz} kHz). Hovor normálne, úroveň pozadia sa prispôsobí automaticky.',
      off: 'Mikrofón je vypnutý.',
      trained: 'Výstupná vrstva je natrénovaná za {ms} ms na {n} príkladoch (tvoje nahrávky a ich zrýchlené a spomalené kópie).',
      saveFailed: 'Do úložiska prehliadača sa nepodarilo uložiť (môže byť plné alebo vypnuté).',
    },
    errors: {
      insecure: 'Mikrofón funguje iba na zabezpečenej stránke: https:// alebo http://localhost. Otvor verziu na webe alebo spusti ./run.sh a použi odkaz na localhost.',
      unsupported: 'Tento prehliadač nemá zvukové funkcie, ktoré ukážka potrebuje (getUserMedia a AudioWorklet). Skús aktuálny Firefox, Chrome, Edge alebo Safari.',
      denied: 'Prístup k mikrofónu bol zamietnutý. Povoľ ho v paneli s adresou a skús to znova.',
      failed: 'Mikrofón sa nepodarilo zapnúť: {error}',
    },
    aria: { meter: 'Úroveň mikrofónu', spec: 'Živý melový spektrogram mikrofónu', heat: 'Aktivita rezervoára pri poslednom slove', grid: 'Mriežka ovládaná hlasom' },
    explain: {
      summary: 'Ako to funguje a čo sa deje s mojím hlasom?',
      simple: [
        'Zvuk z mikrofónu sa premieňa na obrázok toho, ktoré tóny sú práve hlasné (modrý obrázok hore). Keď povieš slovo, tento obrázok putuje do náhodnej siete po malých kúskoch.',
        'Kým sieť počúva, jej aktivita funguje ako odtlačok slova. Počítač sa z tvojich nahrávok (a z ich zrýchlených a spomalených kópií) naučí, ktorý odtlačok patrí ku ktorému slovu.',
        'Doteraz počula iba teba, takže najlepšie funguje s tvojím hlasom, v tej istej miestnosti a s tým istým mikrofónom.',
      ],
      detailed: [
        'Každých 10 ms sa signál z mikrofónu premení na 24 čísel, ktoré opisujú, koľko energie je v jednotlivých frekvenčných pásmach, podobne ako spektrogram vyššie. Detektor hlasovej aktivity vystrihne každé slovo a rámce idú jeden po druhom do náhodného rezervoára s niekoľkými stovkami neurónov. Výstupná vrstva sa pozerá na stav rezervoára v piatich okamihoch počas slova a na jeho priemer a trénuje sa jedinou hrebeňovou regresiou na tvojich nahrávkach. Každá nahrávka sa navyše časovo natiahne do niekoľkých o niečo rýchlejších a pomalších verzií.',
        'Komerčné rozpoznávače kľúčových slov sú hlboké siete CNN natrénované na desiatkach tisíc nahrávok od tisícov ľudí. Tento model počul iba teba, zhruba päťkrát každé slovo, takže najlepšie funguje v tej istej miestnosti, s tým istým mikrofónom a hlasom. Iného človeka si pravdepodobne pomýli. To je daň za to, že potrebuje takmer žiadne dáta a takmer žiadny čas na trénovanie.',
      ],
      privacy: '**Súkromie:** zvuk sa spracúva priamo v tejto stránke a nikdy neopustí tvoje zariadenie. Žiadny zvuk sa neukladá. Ak zaškrtneš „zapamätať si“, uložia sa iba súhrny po 24 číslach, a to do lokálneho úložiska tohto prehliadača. Keď odídeš z tejto karty, mikrofón sa vypne.',
    },
  },

  water: {
    title: 'Vedro vody',
    lead: {
      simple: 'Čo keby bol „mozgom“ obyčajný kúpeľ vody? Dve lopatky robia vlny podľa signálu a počítač sa učí iba to, ako čítať vlnky v 48 bodoch. To stačí na rozlíšenie plynulej vlny od hranatej.',
      detailed: 'Rezervoárom môže byť akýkoľvek systém s dostatočne bohatou dynamikou. Tu počíta simulované jazierko a trénuje sa iba to, ako čítať 48 bodov na jeho hladine.',
    },
    try: 'odškrtni **Nelineárna kamera** a sleduj, ako sa oranžová čiara zmätie, potom ju znova zaškrtni.',
    stats: { accuracy: 'Presnosť, všetky vzorky', settled: 'Presnosť po 1,5 periódy', recall: 'Presnosť spomínania R²', forD: 'pre d = {d}', weights: '({p} bodov{x} + bias)' },
    task: 'Úloha',
    tasks: { shape: 'Rozlíš sínusovú vlnu od obdĺžnikovej', memory: 'Pamätaj si minulosť (spomeň si na vstup spred d krokov)' },
    camera: 'Nelineárna kamera',
    cameraHint: 'Okrem výšky hladiny vidí aj jas ≈ výška², spriemerovaný počas expozície',
    delay: 'Oneskorenie d',
    delayUnit: { one: '{n} krok', few: '{n} kroky', other: '{n} krokov' },
    bucket: 'Vedro',
    damping: 'Tlmenie (ako rýchlo vlnky zaniknú)',
    probes: 'Snímacie body',
    live: 'Živý beh',
    speed: 'Rýchlosť simulácie',
    speedUnit: '{v} vzoriek/s',
    pause: 'Pozastaviť',
    resume: 'Pokračovať',
    splash: 'Špľach!',
    pond: 'Jazierko',
    pondSub: 'motorčeky vľavo · snímacie body sú krúžky',
    motors: 'motorčeky',
    readout: 'Výstup naživo',
    readoutSub: 'najnovšie vpravo',
    curve: 'Ako dlho si voda pamätá?',
    curveSub: 'R² pri spomínaní na vstup spred d krokov',
    legend: { input: 'vstupný signál', answer: 'správna odpoveď (hore = obdĺžnik)', readout: 'výstup', past: 'vstup spred d krokov (ten si má pamätať)' },
    status: {
      making: 'Robím vlny…',
      trained: '{samples} vstupných vzoriek prešlo cez {cells} buniek vody, výstupná vrstva je vyriešená za {ms} ms. Teraz testujem na novom signáli.',
    },
    aria: { pond: 'Simulovaná vodná hladina s motorčekmi a snímacími bodmi', trace: 'Vstupný signál, správna odpoveď a výstup v čase', curve: 'Ako presne si voda pamätá minulosť pri rôznom oneskorení' },
    explain: {
      summary: 'Prečo by mala voda niečo počítať?',
      simple: [
        'Dve lopatky (modré bodky) tlačia vodu hore a dole podľa signálu. Vlnky sa šíria, odrážajú od stien a prekrývajú, takže hladina sa stáva akousi pamäťou toho, čo signál robil pred chvíľou.',
        'Malé krúžky sú 48 meracích bodov, ako keby sa na vodu pozerala kamera. Počítač sa učí iba to, ako tých 48 hodnôt spojiť do odpovede. Samotná voda sa nikdy netrénuje.',
        'Pre vodu vyzerajú plynulá (sínusová) a hranatá (obdĺžniková) vlna veľmi podobne. Skutočná kamera však vidí svetlo, ktoré sa na vlnkách láme, a tento vzťah nie je jednoduchá priamka. Práve táto drobnosť stačí na to, aby ich rozlíšila. Keď kameru odškrtneš, je zmätená.',
        'Vedci to v roku 2003 naozaj urobili, s nádržou vody, motorčekmi z LEGA a webkamerou.',
      ],
      detailed: [
        'Dva „motorčeky“ vľavo tlačia vodu hore a dole podľa vstupného signálu. Vlnky sa šíria, odrážajú od stien a prekrývajú. Hladina v každom okamihu obsahuje zmes toho, čo motorčeky robili za posledné chvíle, takže je fyzickou pamäťou nedávnej histórie vstupu.',
        'Snímacie body sú kamera. Lineárna výstupná vrstva, natrénovaná jedinou hrebeňovou regresiou, spája ich hodnoty do odpovede. Na vode sa netrénuje nič a voda o sínusových ani obdĺžnikových vlnách nič „nevie“.',
        'Vlnky v tejto simulácii sa riadia lineárnou vlnovou rovnicou, takže z výšky hladiny vie lineárna výstupná vrstva vytvoriť iba ďalší lineárny filter vstupu. Na pamätanie si minulosti to stačí, ale prefiltrovaný sínus je stále sínus, takže sa nikdy neustáli na stálej odpovedi „toto je obdĺžnik“. Vypni nelineárnu kameru a výstup bude divoko kmitať. Skutočná kamera, ktorá sa pozerá na vodu presvietenú svetlom, vidí jas, ktorý závisí od hladiny nelineárne, a navyše svetlo spriemeruje počas expozície. Táto jediná nelinearita stačí, aby výstupná vrstva tvary rozlíšila.',
        'Fernando a Sojakka (2003) to urobili naozaj: nádrž s vodou na spätnom projektore, motorčeky z LEGA a webkamera. Vyriešila XOR a rozlíšila vyslovené slová „zero“ a „one“.',
      ],
    },
  },
};
